### ISSUE TITLE
Publish the package for Pulsar Editor

### ISSUE THREAD

**Issue by AlexWayfer** [alexrudd2/linter-stylelint#159]
Hello!

Thanks for your fork.

I've faced with issues from the original package and we've found your fork.

What do you think about publishing a separate package for Pulsar Editor, a fork of Atom Editor?

https://github.com/pulsar-edit/pulsar/issues/645#issuecomment-1639025514

**Comment by confused-Techie** [comment]
I'd like to add on, as one of the maintainers of Pulsar, and lead developers of the backend, I'd be more than happy to assist sorting out any troubles you have publishing, so feel free to give me a ping if needed

**Comment by alexrudd2** [comment]
Can you point me to a guide for how to package for Pulsar?  I've now installed it and read some docs, but couldn't find a publishing guide.

**Comment by confused-Techie** [comment]
@alexrudd2 Thanks a ton for adding me to the project!

But sure, here's our most up to date [docs](https://pulsar-edit.dev/docs/launch-manual/sections/core-hacking/#publishing) on publishing to the PPR.

But it might be a little funkier then implied by those docs.

Essentially, there's two things to keep in mind:

1. PPM will try to tag a release of the project, and upload it to GitHub
2. Then it will need to publish that new version to the PPR (Pulsar Package Registry)

This does mean, that PPM needs some way to interact with Git on your system and your GitHub account. (Ideally, if you have an existing git installation, it should just use that if memory serves), then it will need your Pulsar Account API key to publish to Pulsar.

I know it's a bit weird needing both, but unfortunately Pulsar isn't a part of GitHub anymore, so we can't get away with that like Atom did.

To create your Pulsar account to get your Pulsar Account API Token, just go to the frontend's [signup](https://web.pulsar-edit.dev/login) page.

---

Although if you'd like the "advanced" way to publish, which doesn't require installing Pulsar at all:

1. Get your Pulsar API key
2. Create the tag for your repo and upload that remotely
3. Use something like `curl` to interact with the API of Pulsar directly to publish the package

If you are publishing the package for the first time (like we are here) then you're request will look something like:

`curl -X POST -H "Authorization: <YOUR_PULSAR_API_KEY" https://api.pulsar-edit.dev/api/packages/?repository=alexrudd2/linter-stylelint`

And from there you should be good to go. But feel free to use whatever method you're more comfortable with

**Comment by confused-Techie** [comment]
Or, for the reasons you've added me to the repo, I'd be more than happy to take care of this for you, if you'd like

**Comment by confused-Techie** [comment]
So if you'd like me to handle it just let me know (or even react to this message) and I'll take care of it

**Comment by alexrudd2** [comment]
> So if you'd like me to handle it just let me know (or even react to this message) and I'll take care of it

Sure, go for it.  It'll take me a while to actually learn the codebase and become a "proper" maintainer, anyways.

**Comment by confused-Techie** [comment]
@alexrudd2 Ah I see, well thank you.

So in that case the other big question we have, is this package still shares the name of the previously existing `linter-stylelint`, which of course that package still exists so we can't use the same name.

Is there a name you prefer? Could be simple like `linter-stylelint-pulsar` or `linter-stylelint-redux` so on so forth. But wanting to of course get your thoughts

**Comment by alexrudd2** [comment]
Unless there's some naming convention, `linter-stylelint-pulsar` seems appropriate to me.

**Comment by confused-Techie** [comment]
@alexrudd2 Copy that, `linter-stylelint-pulsar` sounds like a plan to me. I'll get on that as soon as I can

**Comment by confused-Techie** [comment]
Just to keep you updated, I've gone ahead and tried publishing the package to the backend, and it has lead me to discover a bug on the backend.

Where it's defaulting to using the repository name rather than the name defined by the `package.json`, so it thinks the package name is already in use.

So I'll go ahead and resolve that prior to continuing, sorry about that

**Comment by AlexWayfer** [comment]
Do we have progress here?

I'm experiencing a weird UX after installing from CLI.

![image](https://github.com/alexrudd2/linter-stylelint/assets/6510020/5d5e2e47-f787-4767-bb28-2c3cd9b1ed19)

**Comment by AlexWayfer** [comment]
Probably, I've understood the error:

![image](https://github.com/alexrudd2/linter-stylelint/assets/6510020/3bd7340c-c0b8-4e31-8bdd-36f08c6f22db)

It looks like `linter-stylelint-pulsar` has `linter-stylelint` name, which is broken, archived, etc.

**Comment by confused-Techie** [comment]
@AlexWayfer The first issue as you mentioned you figured out, but will still elaborate on, the last part of the message shows us the issue `Request for package information failed: Too Many Requests (429)` which is surprising to say the least. Since iirc the rate limit for unauthenticated endpoints like downloading packages is quite high at several hundred requests per IP per window (each window being 15 minutes). So I hope that isn't a common error you're seeing.

Otherwise as for issues installing it, I was just able to successfully install `linter-stylelint-pulsar`. Although I will say that the `Install` button didn't stop showing it loading, even though the package was completely installed, which I confirmed by checking the package appeared in the "Packages" tab. This may be an issue with Pulsar, or maybe the package isn't returning the activate command as expected, I'm not sure. 

But it should totally be installed, and it may be a good idea to uninstall `linter-stylelint`, not that it's necessarily required, but if for example some keymaps haven't been updated in this fork, that'll possibly cause collisions between the two packages.

**Comment by AlexWayfer** [comment]
> Otherwise as for issues installing it, I was just able to successfully install `linter-stylelint-pulsar`. Although I will say that the `Install` button didn't stop showing it loading, even though the package was completely installed, which I confirmed by checking the package appeared in the "Packages" tab. This may be an issue with Pulsar, or maybe the package isn't returning the activate command as expected, I'm not sure.
> 
> But it should totally be installed, and it may be a good idea to uninstall `linter-stylelint`, not that it's necessarily required, but if for example some keymaps haven't been updated in this fork, that'll possibly cause collisions between the two packages.

No, you didn't understand the issue (my issue).

Nothing was installed.

I've uninstalled and reloaded the editor.

Initial state:

![image](https://github.com/alexrudd2/linter-stylelint/assets/6510020/c882930f-f71f-4aaa-8235-c000668ee639)

Pressing "Install" on the correct package:

![image](https://github.com/alexrudd2/linter-stylelint/assets/6510020/f6a14fc5-8699-46b7-9495-1ad39fc07335)

After around 10 seconds:

![image](https://github.com/alexrudd2/linter-stylelint/assets/6510020/ad72e6ff-497f-4166-96bc-1439c58f0227)

**Comment by confused-Techie** [comment]
Okay wait, @AlexWayfer I take back what I previously said. You are totally correct that it's not installable.

It seems for some reason that while Pulsar is correctly attempting to install `linter-stylelint-pulsar` the backend for some reason is returning a tarball that's older than `4.6.0` (Which is the tarball I published that's needed in order for this package to be identified as different than it's parent fork). Since the backend provides this older tarball, Pulsar then installs an older version that still says it's `linter-stylelint`.

So there is a bug, not because of this package, but apparently the backend for some reason struggled with this, and seems via all the refactors recently there's been a regression the tests didn't catch. So I'll make sure to check it out as soon as I can.

I'll go ahead and track this on [`pulsar-edit/package-backend#236`](https://github.com/pulsar-edit/package-backend/issues/236)

**Comment by AlexWayfer** [comment]
> So there is a bug, not because of this package, but apparently the backend for some reason struggled with this, and seems via all the refactors recently there's been a regression the tests didn't catch. So I'll make sure to check it out as soon as I can.
> 
> I'll go ahead and track this on [`pulsar-edit/package-backend#236`](https://github.com/pulsar-edit/package-backend/issues/236)

Thank you very much.

**Comment by confused-Techie** [comment]
@AlexWayfer I've just seen you're new comment. Yeah I apologize I misunderstood it. But seem to have gotten to the root issue here.

What that means is to fix it, either we need to push an update of this package which should fix what version the backend is attempting to use, or otherwise (and what I'd prefer) I figure out what went wrong on the backend. I'm at work currently so may be some time, but I'll use that issue for tracking of this one. Thanks a ton for pointing this issue out especially since it has a pretty high impact possibility

**Comment by AlexWayfer** [comment]
@confused-Techie no problem here, we'll wait, thank you for your work on all aspects of the wonderful editor.
